# Generated by Django 4.1.3 on 2022-11-08 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brb', '0002_remove_away_away_time_away_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='away',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='away',
            name='return_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
