# Generated by Django 4.1.3 on 2022-11-11 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brb', '0003_alter_away_creation_time_alter_away_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='away',
            name='return_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
