# Generated by Django 4.1.3 on 2022-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='away',
            name='away_time',
        ),
        migrations.AddField(
            model_name='away',
            name='return_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
