# Generated by Django 4.1.3 on 2022-11-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brb', '0005_user_mail_alter_away_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
    ]
