# Generated by Django 4.1.3 on 2023-10-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brb', '0005_alter_away_creation_time'),
        ('brb', '0006_remove_user_mail'),
    ]

    operations = [
    ]
